# Generated by Django 3.2.4 on 2023-08-30 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companymanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('husband_Father', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('relation_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('employee_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('dob', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_of_joining', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('aadhar_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('uan_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pan_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('esi_no', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('esi_account', models.CharField(blank=True, default='yes', max_length=100, null=True)),
                ('pf_no', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pf_account', models.CharField(blank=True, default='yes', max_length=100, null=True)),
                ('pf_date', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('basic_salary', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bank_ac_no', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Image', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companymanager.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpFamaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('relation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('age', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('aadhar', models.ImageField(blank=True, default='', null=True, upload_to='famaly/')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='famaly/')),
                ('emiid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeemanager.employeemodel')),
            ],
        ),
    ]
