# Generated by Django 3.2.4 on 2023-10-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanager', '0002_alter_employeemodel_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='added_by',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
