# Generated by Django 3.2.4 on 2023-08-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanager', '0002_empfamaly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpFamaly',
        ),
    ]
