# Generated by Django 3.2.4 on 2023-08-02 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanager', '0003_delete_empfamaly'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpFamaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('relation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('age', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('aadhar', models.ImageField(blank=True, default='', null=True, upload_to='famaly/')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='famaly/')),
                ('emiid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeemanager.employeemodel')),
            ],
        ),
    ]
