# Generated by Django 3.2.4 on 2023-07-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanager', '0003_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
