# Generated by Django 3.2.4 on 2023-10-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanager', '0003_employeemodel_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='added_by',
            new_name='addedby',
        ),
    ]
