# Generated by Django 3.2.4 on 2023-08-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanager', '0004_empfamaly'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='esi_account',
            field=models.CharField(blank=True, default='yes', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='esi_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
