# Generated by Django 3.2.4 on 2023-08-13 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanager', '0005_auto_20230813_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='esi_number',
            new_name='esi_no',
        ),
    ]
