# Generated by Django 3.2.4 on 2023-06-16 16:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companymanager', '__first__'),
        ('employeemanager', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal_status', models.CharField(default=1, max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('total_days', models.IntegerField()),
                ('attendance_days', models.IntegerField()),
                ('month', models.CharField(default=1, max_length=100)),
                ('year', models.CharField(default=1, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companymanager.company')),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeemanager.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
