# Generated by Django 3.2.4 on 2023-07-31 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanager', '0001_initial'),
        ('attendencemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancemodel',
            name='payslip',
            field=models.FileField(blank=True, default='', null=True, upload_to='payslips/'),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='employee_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attend', to='employeemanager.employeemodel'),
        ),
    ]
