# Generated by Django 3.2.4 on 2023-07-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendencemanager', '0002_auto_20230731_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='payslip',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
