# Generated by Django 3.2.4 on 2023-08-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendencemanager', '0003_alter_attendancemodel_payslip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='payslip',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
