# Generated by Django 3.2.4 on 2023-08-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendencemanager', '0004_alter_attendancemodel_payslip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodel',
            name='user',
        ),
    ]
