# Generated by Django 3.2.4 on 2023-08-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('companycode', models.CharField(default='', max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(default='logo/freelogo.png', upload_to='comapanydocs/')),
                ('pf_persentage', models.CharField(blank=True, default='12', max_length=12, null=True)),
                ('esi_persentage', models.CharField(blank=True, default='12', max_length=12, null=True)),
            ],
        ),
    ]
