# Generated by Django 3.2.4 on 2023-07-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companycode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
