# Generated by Django 3.2.4 on 2023-07-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pf_persentage',
            field=models.CharField(blank=True, default='12', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='psi_persentage',
            field=models.CharField(blank=True, default='12', max_length=12, null=True),
        ),
    ]
