# Generated by Django 3.2.4 on 2023-07-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companymanager', '0002_auto_20230724_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='psi_persentage',
            new_name='esi_persentage',
        ),
    ]
