# Generated by Django 3.2.4 on 2023-08-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companymanager', '0004_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, default='logo/freelogo.png', max_length=200, null=True),
        ),
    ]
