# Generated by Django 3.2.4 on 2023-08-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companymanager', '0001_initial'),
        ('employeemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='salaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal_status', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('updated_date', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('BasicSalary', models.CharField(blank=True, max_length=20, null=True)),
                ('DearnessAllowance', models.CharField(blank=True, max_length=20, null=True)),
                ('HouseRentAllowance', models.CharField(blank=True, max_length=20, null=True)),
                ('ConveyanceAllowance', models.CharField(blank=True, max_length=20, null=True)),
                ('MedicalAllowance', models.CharField(blank=True, max_length=20, null=True)),
                ('SpecialAllowance', models.CharField(blank=True, max_length=20, null=True)),
                ('TaxDeductedatSource', models.CharField(blank=True, max_length=20, null=True)),
                ('Professionaltax', models.CharField(blank=True, max_length=20, null=True)),
                ('pf_deductiion', models.CharField(blank=True, max_length=20, null=True)),
                ('esi_deduction', models.CharField(blank=True, max_length=20, null=True)),
                ('netSal', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companymanager.company')),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empsalary', to='employeemanager.employeemodel')),
            ],
        ),
    ]
