# Generated by Django 3.2.4 on 2023-07-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeemanager', '0001_initial'),
        ('salarymanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarymodel',
            name='employee_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empsalary', to='employeemanager.employeemodel'),
        ),
    ]
