# Generated by Django 3.2.4 on 2023-07-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanager', '0002_alter_salarymodel_employee_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarymodel',
            name='user',
        ),
    ]
