# Generated by Django 3.2.4 on 2023-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanager', '0003_remove_salarymodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarymodel',
            name='esi_deduction',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarymodel',
            name='pf_deductiion',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
