# Generated by Django 3.2.4 on 2023-07-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanager', '0004_auto_20230721_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarymodel',
            old_name='EmployeeProvidentFund',
            new_name='netSal',
        ),
    ]
