# Generated by Django 3.2.4 on 2023-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanager', '0005_rename_employeeprovidentfund_salarymodel_netsal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarymodel',
            name='BasicSalary',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='ConveyanceAllowance',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='DearnessAllowance',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='HouseRentAllowance',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='MedicalAllowance',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='Professionaltax',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='SpecialAllowance',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='TaxDeductedatSource',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='esi_deduction',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='netSal',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='pf_deductiion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='sal_status',
            field=models.CharField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='updated_date',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
