# Generated by Django 3.2.4 on 2023-07-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salarymanager', '0006_auto_20230724_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarymodel',
            name='BasicSalary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='ConveyanceAllowance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='DearnessAllowance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='HouseRentAllowance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='MedicalAllowance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='Professionaltax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='SpecialAllowance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='TaxDeductedatSource',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='esi_deduction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='netSal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='pf_deductiion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
